export const report = {
  ADMIN_READ: 'REPORT_ADMIN_READ',
  ADMIN_READ_SUCCESS: 'REPORT_ADMIN_READ_SUCCESS',
  ADMIN_READ_FAILURE: 'REPORT_ADMIN_READ_FAILURE',
  ADMIN_UPDATE_BY_ID: 'REPORT_ADMIN_UPDATE_BY_ID',
  ADMIN_UPDATE_BY_ID_SUCCESS: 'REPORT_ADMIN_UPDATE_BY_ID_SUCCESS',
  ADMIN_UPDATE_BY_ID_FAILURE: 'REPORT_ADMIN_UPDATE_BY_ID_FAILURE',
};

export const loader = {
  ADD_ACTION: 'LOADER_ADD_ACTION',
  REMOVE_ACTION: 'LOADER_REMOVE_ACTION',
};
